### PR TITLE
Carael/bump mongo driver

### PR DESCRIPTION
**Pull request by Carael**
Bump to mongo 2.29.0

### CODE REVIEW

**Comment by sebbebebbe** [comment]
Any chance we could get the MongoDb-driver bumped to 3.0.0 instead?

**Comment by Carael** [comment]
> Any chance we could get the MongoDb-driver bumped to 3.0.0 instead?

Bump to 3.0.0 is in plans but firstly we would like to update to mongo driver 2.30.0 and bump version to 4.0.0 since it's also a breaking change because of [strong naming since version 2.28.0](https://www.mongodb.com/community/forums/t/net-c-driver-strong-naming/291649/2).

Most likely mongo extensions release with driver 3.0.0 will have a version 5.0.0 (contains breaking changes).

**Review by nscheibe — DISMISSED** [review]
Great work.

**Review by nscheibe — DISMISSED** [review]
Great work

**Review by nscheibe — APPROVED** [review]
well done

**Comment by Carael** [comment]
thanks @nscheibe for help with that one

**Pull request merged**
