### PR TITLE
Set default value for missing nullable fields

### PR DESCRIPTION
**Pull request by TimHolzherr**
Set default value for missing nullable fields

If we add a nullable field to a immutable class we could no longer desterilize documents which have been stored without the new field. By setting the default value for nullable fields to null we can resolve this issue.

### CODE REVIEW

**Comment by TimHolzherr** [comment]
Hi @glucaci 
Dario and I discussed about the issue that we need a migration to add a nullable field to one of our classes and maybe just setting "null" as default value for nullable fields would already solve our issue. What are your thought?

**Review by glucaci — APPROVED** [review]

**Pull request merged**
