### PR TITLE
Upgrade MongoDB.Driver dependency to version 2.24.0

### PR DESCRIPTION
**Pull request by 0xced**
And implement the new required `IMongoCollection<T>` members: `DistinctMany` + `DistinctManyAsync`.

### CODE REVIEW

**Comment by 0xced** [comment]
Any chance you have a look, @glucaci and/or @nscheibe? It should be pretty straightforward, it's just another breaking change in the MongoDB driver, like #87. ¯\\\_(ツ)\_/¯

**Comment by 0xced** [comment]
Ping @glucaci and @nscheibe. Any chance for a new release?

**Review by PascalSenn — APPROVED** [review]
LGTM

**Comment by PascalSenn** [comment]
@0xced 

Sorry that this took so long

**Pull request merged**
