### PR TITLE
Added Transaction scope integration

### PR DESCRIPTION
**Pull request by PascalSenn**
Adds integration for Transaction Scope

### CODE REVIEW

**Comment by glucaci** [comment]
Very nice, let's finish this, it's very good addition to any mongo application.
Let me know if you need some help.

P.S.: need to sign the CLA :)

**Comment by PascalSenn** [comment]
@glucaci  it is finished :) 
I also did sign the CLA but it doesnt work

**Comment by PascalSenn** [comment]
Ah the build fails, will have a look

**Review by glucaci — DISMISSED** [review]
Very useful feature 👍

**Review by nscheibe — APPROVED** [review]
Well done

**Pull request merged**
